Remove support for put_map_exact without a source map
Using the exact operator (':=') is only allowed when an existing map
is being updated. Thus the following causes a compilation error:

  #{k:=v}

Therefore there is no need to support the put_map_exact instruction
without a source map.