Eliminate crash when optimization passes are disabled
When compiling the following code with optimization passes disabled:

    foo() ->
        ([<<bad/utf8>>] =
             try
                 [whatever]
             catch
                 _:_ when false ->
                     ok
             end) ! (some_atom ++ <<>>).

`beam_validator` rejects the code with the following message:

    some_module:1: function foo/0+11:
      Internal consistency check failed - please report this bug.
      Instruction: {get_hd,{literal,[whatever]},{x,0}}
      Error:       {literal_not_allowed,{literal,[whatever]}}:

All optimization passes are supposed to be optional, so this crash is
not acceptable even though the code is nonsensical. Eliminate the
crash by having `beam_ssa_pre_codegen` re-run its code cleaning
pass until there are no more unreachable blocks.