Fix compilation with `--enable-vm-probes`
... broken by 3ac08f9b.

Compilation error:
```
beam/erl_message.c: In function 'erts_send_message':
beam/erl_message.c:753:56: error: macro "copy_struct" requires 4 arguments, but only 3 given
   utag = copy_struct(DT_UTAG(sender), dt_utag_size, ohp);
                                                        ^
beam/erl_message.c:753:10: error: 'copy_struct' undeclared (first use in this function)
   utag = copy_struct(DT_UTAG(sender), dt_utag_size, ohp);
          ^
beam/erl_message.c:753:10: note: each undeclared identifier is reported only once for each function it appears in
```