Eliminate another crash when optimization passes are disabled
When compiling the following code with the SSA-based optimization
passes disabled:

    foo(#{{tag,whatever} := true,
          #{} := <<bad_integer,0:(is_integer(a))>>} =
            #{[something] := 42}) ->
        ok.

The `beam_validator` pass rejects the code with the following message:

    t:1: function foo/1+6:
      Internal consistency check failed - please report this bug.
      Instruction: {get_map_elements,
                       {f,1},
                       {x,0},
                       {list,
                           [{literal,[something]},
                            {x,2},
                            {literal,#{}},
                            {x,2},
                            {literal,{tag,whatever}},
                            {x,1}]}}
      Error:       conflicting_destinations:

All optimization passes are supposed to be optional, so this crash is
not acceptable even though the code is nonsensical.