Set UTF-8 locale on github action builds
Before, locale what set to "POSIX" which would cause java compiler
to assume pure ASCII source file and reject UTF-8 characters.

error: unmappable character (0xC3) for encoding US-ASCII