beam_jump: Be more careful when sharing function calls
The code in #6222 would fail to compile like this:

    t:1: function from/1+58:
      Internal consistency check failed - please report this bug.
      Instruction: {call_ext,1,{extfunc,lists,flatten,1}}
      Error:       {allocated,undecided}:

The reason was an unsafe optimization made by the `beam_jump`
pass. Avoid the problem by only sharing function calls if it
can be seen that the stack frames at the time of the calls
have the same size.

Closes #6222