beam_ssa_pre_codegen: Fix an internal consistency failure
The following function:

    is_two_tuple(Arg) ->
        case is_tuple(Arg) of
            false -> false;
            true -> tuple_size(Arg) == 2
        end.

would cause an internal consistency failure:

    Internal consistency check failed - please report this bug.
    Instruction: {bif,tuple_size,{f,0},[{x,0}],{z,0}}
    Error:       {invalid_store,{z,0},{integer,[]}}: