Add missing include statements in in6addr tests
Compilation is failing on macOS Big Sur due to in6addr_any and in6addr_loopback
being redeclared. The underlying issue is that the tests for these are failing
due to missing include statements:

conftest.c:197:1: error: implicitly declaring library function 'printf'
with type 'int (const char *, ...)' [-Werror,-Wimplicit-function-declaration]
printf("%d", in6addr_any.s6_addr[16]);
^
conftest.c:197:1: note: include the header <stdio.h> or explicitly provide
a declaration for 'printf'

ERL-1306