beam_validator: Fix validation failure for failing apply
Compiling the following code:

    foo() ->
        try
            receive
                _ ->
                    42
            end:name()
        catch
            _:_ ->
                error
        end.

would cause a validation error because `beam_validator` would not
recognize that `42:name()` would always fail:

    t:1: function foo/0+14:
      Internal consistency check failed - please report this bug.
      Instruction: {jump,{f,4}}
      Error:       {illegal_branch,try_handler,4}: