Fix race related to precompiled header during compilation
Files matching `erts/emulator/beam/jit/$(JIT_ARCH)/%.cpp` are compiled
with the command line flag `-include $(ASMJIT_PCH_SRC)`, but as there
is no dependency on `$(ASMJIT_PCH_OBJ)` the compilation of the C++
module will race with the precompilation of `$(ASMJIT_PCH_SRC)`. The
missing dependency leads to intermittent build failures as g++ will,
when reading an incomplete precompiled header, abort with `cc1plus:
error: while reading precompiled header: No such file or directory`.

Avoid this race by adding a dependency on `$(ASMJIT_PCH_OBJ)` just as
for files matching `erts/emulator/beam/jit/%.cpp` and
`erts/emulator/asmjit/%.cpp`.