Provide more helpful error messages when loading old BEAM files
After the changes in c7ddbcbe7d95 (#5233), attempting to load a BEAM
file compiled with OTP 20 or earlier would result in the following
error report:

    =ERROR REPORT==== 30-Sep-2021::09:28:25.626580 ===
    beam/beam_load.c(130): Error loading module t:
      missing atom table

Provide a more helpful error report if the BEAM file contains
an old-style atom table:

    =ERROR REPORT==== 30-Sep-2021::09:22:24.235402 ===
    beam/beam_load.c(133): Error loading module t:
      please re-compile this module with an Erlang/OTP 25 compiler

While we are at it, also update all similar messages by the
loader to say "Erlang/OTP 25 compiler" instead of "25 compiler".
(The missing "OTP" made more sense when releases were named
with an "R" prefix, such as R17.)