Fix internal compiler error for map_get/2
Code such as that the following:

    Val = map_get(a, Map),
    Map#{a:=z}   %Could be any map update

would incorrectly cause an internal consistency check failure:

   Internal consistency check failed - please report this bug.
   Instruction: {put_map_exact,{f,0},{x,0},{x,0},1,{list,[{atom,a},{atom,z}]}}
   Error:       {bad_type,{needed,map},{actual,term}}:

Update beam_validator so that it understands that the second
argument for map_get/2 is a map.