Specify encoding when running javadoc
This fixes the following issues during javadoc file processing stage:

```
(cd ../../java_src;javadoc -sourcepath . -d ../doc/html/java \
	-windowtitle 'Java-Erlang Interface Library' com.ericsson.otp.erlang)
Loading source files for package com.ericsson.otp.erlang...
./com/ericsson/otp/erlang/OtpGenericTransportFactory.java:2: error: unmappable character (0xC3) for encoding US-ASCII
 * Copyright 2022 J??r??me de Bretagne
                   ^
./com/ericsson/otp/erlang/OtpGenericTransportFactory.java:2: error: unmappable character (0xA9) for encoding US-ASCII
 * Copyright 2022 J??r??me de Bretagne
                    ^
./com/ericsson/otp/erlang/OtpGenericTransportFactory.java:2: error: unmappable character (0xC3) for encoding US-ASCII
 * Copyright 2022 J??r??me de Bretagne
                      ^
./com/ericsson/otp/erlang/OtpGenericTransportFactory.java:2: error: unmappable character (0xB4) for encoding US-ASCII
 * Copyright 2022 J??r??me de Bretagne
                       ^
4 errors
```

Followup to commit 6bcfd5aaa66c208251357db3d5e8a2927a7af4d1.

Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>