beam_validator: Eliminate type mismatch
When compiling the following code:

    f1({X}) when X; (X orelse false) ->
        (X orelse {}),
        [
            {X}#{
                f2() orelse X => []
            }
         || _ <- []
        ].

    f2() ->
        0.

the `beam_validator` pass rejects it:

    call_only:1: function f1/1+27:
      Internal consistency check failed - please report this bug.
      Instruction: {call_only,3,{f,16}}
      Error:       {bad_arg_type,
                       {x,1},
                       {t_tuple,1,true,#{1 => {t_atom,[false,true]}}},
                       {t_union,none,none,none,
                           [{{1,{t_atom,[false]}},
                             {t_tuple,1,true,#{1 => {t_atom,[false]}}}},
                            {{1,{t_atom,[true]}},
                             {t_tuple,1,true,#{1 => {t_atom,[true]}}}}],
                           none}}:

What happens here is that when types are updated in different ways,
the result will be different. That is not supposed to happen; there
should be one canonical type representation regardless how it's
reached.

This commit resolves the bug for this particular example, but a more
general solution might be needed.

Closes #6458